name: Node formatting

on:
  push:
    branches: [ master, develop ]
  pull_request:
    branches: [ master, develop ]

jobs:
  formatting:
    runs-on: ubuntu-latest

    steps:
      - name: format - Prettify code
        uses: creyD/prettier_action@v3.1
        # with:
          # This part is also where you can pass other options, for example:
          # prettier_options: --write **/*.{js,ts,md}
